/*
 * This source file was generated by the Gradle 'init' task
 */
package _Java1._0;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void test() {
        assertTrue(true);
    }
}
