/*
 * This source file was generated by the Gradle 'init' task
 */
package _Java1._0;

public class FirstDayOfProgramming {
    public static void main(String[] args) {
    	System.out.println("Hello World");
    }
}
